/********************************************************************
* class Name:   UpdateProductPriceToRunBatchBySche
* Test Class:   GoodsTest
* Purpose:  通过定时器批量修改产品价格操作
* Author: king frk(1612017127@qq.com)
* Created Date: 2021/1/4
* Modify Description: 
* 1. 修改逻辑 (Joe 2020-7-27）
********************************************************************/
global class UpdateProductPriceToRunBatchBySche implements Schedulable {
    global void execute(SchedulableContext sc) {
        
    }
}